cmake_minimum_required(VERSION 4.0)
project(Afterlife_Engine)
include(FetchContent)

set(CMAKE_CONFIGURATION_TYPES "Debug;Release;Packaging;Testing;" CACHE STRING "" FORCE)
set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED TRUE)

set(SDL_SHARED OFF)

set(STEAMWORKS_PATH "${CMAKE_SOURCE_DIR}/libs/Steamworks-SDK")
set(STEAM_ENABLED ${OPTION_DISABLED})

set(OPTION_DISABLED 0)
set(OPTION_ENABLED 1)


# thank god for CLion
add_executable(Afterlife_Engine
        src/Engine/Core/Handlers/AssetRepo.cpp
        src/Engine/Core/Handlers/AssetRepo.h
        src/Engine/Core/Handlers/AudioHandler.cpp
        src/Engine/Core/Handlers/AudioHandler.h
        src/Engine/Core/Handlers/Input.cpp
        src/Engine/Core/Handlers/Input.h
        src/Engine/Core/Handlers/PhysicsHandler.cpp
        src/Engine/Core/Handlers/PhysicsHandler.h
        src/Engine/Core/Handlers/RenderHandler.cpp
        src/Engine/Core/Handlers/RenderHandler.h
        src/Engine/Core/Handlers/RNGHandler.cpp
        src/Engine/Core/Handlers/RNGHandler.h
        src/Engine/Core/Engine.cpp
        src/Engine/Core/Engine.h
        src/Engine/Core/World/Sector.cpp
        src/Engine/Core/World/Sector.h
        src/Engine/gl/include/glad/glad.h
        src/Engine/gl/include/KHR/khrplatform.h
        src/Engine/gl/include/stb_image.cpp
        src/Engine/gl/include/stb_image.h
        src/Engine/gl/src/glad.c
        src/Engine/EngineWidgets/StatisticsWidgets.cpp
        src/Engine/EngineWidgets/StatisticsWidgets.h
        src/Engine/EngineWidgets/TimingsWidget.cpp
        src/Engine/EngineWidgets/TimingsWidget.h
        src/Engine/imgui/backends/imgui_impl_opengl3.cpp
        src/Engine/imgui/backends/imgui_impl_opengl3.h
        src/Engine/imgui/backends/imgui_impl_opengl3_loader.h
        src/Engine/imgui/backends/imgui_impl_sdl3.cpp
        src/Engine/imgui/backends/imgui_impl_sdl3.h
        src/Engine/imgui/imconfig.h
        src/Engine/imgui/imgui.cpp
        src/Engine/imgui/imgui.h
        src/Engine/imgui/imgui_demo.cpp
        src/Engine/imgui/imgui_draw.cpp
        src/Engine/imgui/imgui_internal.h
        src/Engine/imgui/imgui_tables.cpp
        src/Engine/imgui/imgui_widgets.cpp
        src/Engine/imgui/implot.cpp
        src/Engine/imgui/implot.h
        src/Engine/imgui/implot_demo.cpp
        src/Engine/imgui/implot_internal.h
        src/Engine/imgui/implot_items.cpp
        src/Engine/imgui/imstb_rectpack.h
        src/Engine/imgui/imstb_textedit.h
        src/Engine/imgui/imstb_truetype.h
        src/Engine/Core/System/OS.cpp
        src/Engine/Core/System/OS.h
        src/Engine/Stores/Steam/SteamStore.cpp
        src/Engine/Stores/Steam/SteamStore.h
        src/Engine/Types/AssetMission.h
        src/Engine/Types/Audio.h
        src/Engine/Types/Rendering/Color.h
        src/Engine/Types/CommonTypes.h
        src/Engine/Types/CoreSystems.h
        src/Engine/Types/Input/KeyCodes.h
        src/Engine/Math/Math.h
        src/Engine/Types/Nullable.h
        src/Engine/Types/Rendering/RenderMission.h
        src/Engine/Types/SpawnArgs.cpp
        src/Engine/Types/SpawnArgs.h
        src/Engine/Math/Transform.cpp
        src/Engine/Math/Transform.h
        src/Engine/Types/Version.cpp
        src/Engine/Types/Version.h
        src/Engine/Core/Widget.cpp
        src/Engine/Core/Widget.h
        src/Engine/Util/BitwiseMacros.h
        src/Engine/Util/Env.h
        src/Engine/Util/Log.cpp
        src/Engine/Util/Log.h
        src/Engine/EngineDefines.h
        src/Engine/Entry-Point.cpp
        src/Game/GameDefines.h
        src/WidroloFramework.h
        src/Engine/Math/Vector.h
        src/Engine/Math/Shapes.h
        src/Engine/Math/Matrix.h
        src/Engine/Math/Vectors/Vectors.cpp
        src/Engine/Math/Vectors/VecMath.cpp
        src/Engine/Math/Other/Quaternion.h
        src/Engine/Math/Other/Quaternion.cpp
        src/Engine/Math/Matrices/MatrixMath.cpp
        src/Engine/Math/Functions/Trigonometry.cpp
        src/Engine/Math/Functions/Power.cpp
        src/Engine/Util/Timer.cpp
        src/Engine/Util/Timer.h
        src/Engine/Types/Input/InputDevice.h
        src/Engine/EngineWidgets/PeripheralWidget.cpp
        src/Engine/EngineWidgets/PeripheralWidget.h
        src/Engine/Core/Handlers/WidgetHandler.cpp
        src/Engine/Core/Handlers/WidgetHandler.h
        src/Engine/EngineWidgets/SystemWidget.cpp
        src/Engine/EngineWidgets/SystemWidget.h
        src/Engine/EngineWidgets/GameSystemWidget.cpp
        src/Engine/EngineWidgets/GameSystemWidget.h
        src/Engine/EngineWidgets/SectorWatchWidget.h
        src/Engine/EngineWidgets/SectorWatchWidget.cpp
        src/Engine/EngineWidgets/EngineControlWidget.cpp
        src/Engine/EngineWidgets/EngineControlWidget.h
        src/Engine/EngineWidgets/PhysicsWatchWidget.cpp
        src/Engine/EngineWidgets/PhysicsWatchWidget.h
        src/Engine/Core/System/Memory.cpp
        src/Engine/Core/System/Memory.h
        src/Engine/WTL/vector.h
        src/Engine/WTL/allocator.h
        src/Engine/WTL/deque.h
        src/Engine/UI/UIWidget.cpp
        src/Engine/UI/UIWidget.h
        src/Engine/UI/UIElement.h
        src/Engine/UI/Elements/Buttons/Button.cpp
        src/Engine/UI/Elements/Buttons/Button.h
        src/Engine/UI/Elements/Containers/Container.cpp
        src/Engine/UI/Elements/Containers/Container.h
        src/Engine/UI/Elements/Dropdowns/Dropdown.cpp
        src/Engine/UI/Elements/Dropdowns/Dropdown.h
        src/Engine/UI/Elements/Images/Image.cpp
        src/Engine/UI/Elements/Images/Image.h
        src/Engine/UI/Elements/InputFields/TextInput.cpp
        src/Engine/UI/Elements/InputFields/TextInput.h
        src/Engine/UI/Elements/Labels/TextLabel.cpp
        src/Engine/UI/Elements/Labels/TextLabel.h
        src/Engine/UI/Elements/Seperators/Seperator.cpp
        src/Engine/UI/Elements/Seperators/Seperator.h
        src/Engine/UI/Elements/Sliders/Slider.cpp
        src/Engine/UI/Elements/Sliders/Slider.h
        src/Engine/UI/Elements/Toggles/Checkbox.cpp
        src/Engine/UI/Elements/Toggles/Checkbox.h
        src/Engine/WTL/queue.h
        src/Engine/Types/Rendering/Color.cpp
        src/Engine/UI/UIParser.cpp
        src/Engine/UI/UIParser.h
        src/Engine/Core/Handlers/JobHandler.cpp
        src/Engine/Core/Handlers/JobHandler.h
        src/Engine/Types/Jobs/WorkerThreadState.h
        src/Engine/Core/System/ThreadScheduler.cpp
        src/Engine/Core/System/ThreadScheduler.h
        src/Engine/Types/Jobs/Job.h
        src/Engine/Types/Jobs/JobLengthEstimation.h
        src/Engine/Types/Physics/OverlapResult.h
        src/Engine/WTL/map.h
        src/Editor/EditorDefines.h
        src/Editor/Core/Editor.cpp
        src/Editor/Core/Editor.h
        src/Editor/Types/EditorSystems.h
        src/Editor/Core/Handlers/EditorUIHandler.cpp
        src/Editor/Core/Handlers/EditorUIHandler.h
        src/Editor/EditorWidgets/AboutWidget.cpp
        src/Editor/EditorWidgets/AboutWidget.h
        src/Editor/Core/Handlers/MenubarHandler.cpp
        src/Editor/Core/Handlers/MenubarHandler.h
        src/Editor/Types/MenubarItem.h
        src/Editor/MenubarItems/File/Menubar_Exit.cpp
        src/Editor/MenubarItems/File/Menubar_Exit.h
        src/Editor/MenubarItems/File/Menubar_RunGame.cpp
        src/Editor/MenubarItems/File/Menubar_RunGame.h
        src/Editor/EditorWidgets/SectorList.cpp
        src/Editor/EditorWidgets/SectorList.h
        src/Editor/EditorWidgets/EntryList.cpp
        src/Editor/EditorWidgets/EntryList.h
        src/Editor/EditorWidgets/AssetBrowser.cpp
        src/Editor/EditorWidgets/AssetBrowser.h
        src/Editor/EditorWidgets/EntryData.cpp
        src/Editor/EditorWidgets/EntryData.h
        src/Editor/EditorWidgets/Viewport.cpp
        src/Editor/EditorWidgets/Viewport.h
        src/Editor/MenubarItems/Help/Menubar_About.cpp
        src/Editor/MenubarItems/Help/Menubar_About.h
        src/Editor/Types/EditorState.h
        src/Game/Core/Game.cpp
        src/Game/Core/Game.h
        src/Engine/WTL/list.h
        src/Engine/Core/System/Iris.h
        src/Engine/Types/Rendering/ShaderSettings.h
        src/Engine/Types/Rendering/MeshInfo.h
        src/Engine/Types/Rendering/LineInfo.h
        src/Engine/Types/Rendering/TextureInfo.h
        src/Engine/Types/DebugFlags.h
        src/Engine/EngineWidgets/DebugFlagsWidget.cpp
        src/Engine/EngineWidgets/DebugFlagsWidget.h
        src/Engine/Types/Rendering/PostProcessShader.h
        src/Engine/Types/AI/Behaviour/BehaviourTree.h
        src/Engine/Types/AI/Behaviour/BehaviourNode.h
        src/Engine/Types/AI/Behaviour/BehaviourExecutionStatus.h
        src/Engine/Types/Blackboard.h
        src/Engine/Types/BlackboardVariable.h
        src/Engine/Types/BlackboardVariable.cpp
        src/Engine/Types/AI/Behaviour/BehaviourNode.cpp
        src/Engine/Types/AI/Behaviour/Control/SelectorNode.cpp
        src/Engine/Types/AI/Behaviour/Control/SelectorNode.h
        src/Engine/Types/AI/Behaviour/Control/ParallelNode.cpp
        src/Engine/Types/AI/Behaviour/Control/ParallelNode.h
        src/Engine/Types/AI/Behaviour/Control/SequenceNode.cpp
        src/Engine/Types/AI/Behaviour/Control/SequenceNode.h
        src/Engine/Types/AI/Behaviour/Control/InverterNode.cpp
        src/Engine/Types/AI/Behaviour/Control/InverterNode.h
        src/Engine/Types/AI/Behaviour/BehaviourTree.cpp
        src/Engine/Types/AI/Behaviour/Control/BranchNode.cpp
        src/Engine/Types/AI/Behaviour/Control/BranchNode.h
        src/Engine/Core/System/GPUSettings.h
        src/Engine/imgui/backends/imgui_impl_vulkan.cpp
        src/Engine/Types/Rendering/ShaderInfo.h
        src/Game/Gameplay/Freecam.cpp
        src/Game/Gameplay/Freecam.h
        src/Engine/gl/gltf/tiny_gltf_v3.c
        src/Engine/Types/Rendering/InstanceData.h
        src/Engine/Types/Rendering/Iris/InstThreadedList.cpp
        src/Engine/Types/Rendering/Iris/InstThreadedList.h
        src/Engine/EngineWidgets/RenderWatchWidget.cpp
        src/Engine/EngineWidgets/RenderWatchWidget.h
        src/Engine/Types/Rendering/ShaderDefinition.h
        src/Engine/Types/Refcounted.h
        src/Engine/Types/Rendering/MaterialDefinition.h
        src/Engine/Types/Rendering/ShaderDefinition.cpp
        src/Engine/Types/Rendering/MaterialDefinition.cpp
        src/Engine/Util/TextureSwizzler.cpp
        src/Engine/Util/TextureSwizzler.h
        src/Engine/Types/Rendering/Iris/IrisAssetComms.h
        src/Game/Types/GameSystems.h
        src/Engine/Types/Rendering/LightingInfo.h
        src/Engine/Core/Handlers/TimeHandler.cpp
        src/Engine/Core/Handlers/TimeHandler.h
        src/Engine/Types/Time/Date.h
        src/Engine/Types/Time/Month.h
        src/Engine/Types/Time/Time.h
        src/Engine/Types/Time/Day.h
        src/Engine/Types/Time/Time.cpp
        src/Engine/Types/Time/Date.cpp
        src/Engine/EngineWidgets/TimeWatchWidget.cpp
        src/Engine/EngineWidgets/TimeWatchWidget.h
        src/Engine/Core/System/Haptic.h
        src/Engine/Types/Input/InputPatch.h
        src/Engine/Core/System/HapticSDL.cpp
        src/Engine/Core/System/Haptic/SDL/SDLFetching.cpp
        src/Engine/Core/System/Haptic/SDL/SDLFetching.h
        src/Engine/Core/System/Haptic/SDL/SDLContext.h
        src/Engine/Types/Input/InputSense.h
        src/Engine/Core/System/Haptic/SDL/SDLTypes.h
        src/Engine/Types/ValueBelt.h
        src/Engine/Core/System/Haptic/SDL/SDLCore.cpp
        src/Engine/Core/System/Haptic/SDL/SDLCore.h
        src/Engine/Types/Input/KeyCodes.cpp
        src/Engine/Core/System/Haptic/SDL/SDLHelpers.cpp
        src/Engine/Core/System/Haptic/SDL/SDLHelpers.h
        src/Engine/Types/Input/InputSense.cpp
        src/Engine/Types/Rendering/DDS.cpp
        src/Engine/Types/Rendering/DDS.h
        src/Engine/Types/Physics/BodyHandle.h
        src/Engine/Types/Physics/BodyType.h
        src/Engine/Types/Physics/PhysicsBody.h
        src/Editor/MenubarItems/File/Menubar_RunTest.cpp
        src/Editor/MenubarItems/File/Menubar_RunTest.h
        src/Testing/TestingDefines.h
        src/Testing/Core/Tester.cpp
        src/Testing/Core/Tester.h
        src/Testing/Types/Test.h
        src/Testing/Types/TestCollection.cpp
        src/Testing/Types/TestCollection.h
        src/Testing/Types/Testable.h
        src/Testing/Tests/Types/Version_Test.cpp
        src/Testing/Tests/Types/Version_Test.h
        src/Testing/Types/Testable.h
        src/Testing/Types/EndTestable.h
        src/Testing/Types/TestStatistics.h
        src/Engine/Util/Handles.h
        src/Engine/Core/System/Iris/Vulkan/IrisLifetime.cpp
        src/Engine/Core/System/Iris/Vulkan/IrisResources.cpp
        src/Engine/Core/System/Iris/Vulkan/IrisSwapchain.cpp
        src/Engine/Core/System/Iris/Vulkan/IrisRecording.cpp
        src/Engine/Core/System/Iris/Vulkan/IrisBinding.cpp
        src/Engine/Core/System/Iris/Vulkan/IrisCommands.cpp
        src/Engine/Core/System/Iris/Vulkan/IrisImGui.cpp
        src/Engine/Core/System/Iris/Vulkan/IrisStatistics.cpp
        src/Engine/Core/System/Iris/Vulkan/Helpers/Init.cpp
        src/Engine/Core/System/Iris/Vulkan/Helpers/Init.h
        src/Engine/Core/System/Iris/Vulkan/IrisInit.cpp
        src/Engine/Core/System/Iris/Vulkan/IrisGlobals.h
        src/Engine/Core/System/Iris/Vulkan/Helpers/Types.h
        src/Engine/Types/Rendering/Iris/Handles.h
        src/Engine/Types/Rendering/Iris/Formats.h
        src/Engine/Types/Rendering/Iris/FixedFunction.h
        src/Engine/Types/Rendering/Iris/Descriptors.h
        src/Engine/Types/Rendering/Iris/Usage.h
        src/Engine/Types/Rendering/Iris/Resource.h
        src/Engine/Types/Rendering/Iris/Pipeline.h
        src/Engine/Types/Rendering/Iris/Framebuffer.h
        src/Engine/Types/Rendering/Iris/RenderCompute.h
        src/Engine/Types/Rendering/Iris/Init.h
        src/Engine/Core/System/Iris/Vulkan/Helpers/Helpers.h
        src/Engine/Core/System/Iris/Vulkan/Helpers/Helpers.cpp
        src/Engine/Core/System/Iris/Vulkan/Helpers/Allocators.cpp
        src/Engine/Core/System/Iris/Vulkan/Helpers/Allocators.h
        src/Engine/Core/System/Iris/Vulkan/Helpers/Queues.cpp
        src/Engine/Core/System/Iris/Vulkan/Helpers/Queues.h
        src/Engine/Core/System/Iris/Vulkan/Helpers/Swapchain.cpp
        src/Engine/Core/System/Iris/Vulkan/Helpers/Swapchain.h
        src/Engine/Core/System/Iris/Vulkan/Helpers/Sync.h
        src/Engine/Core/System/Iris/Vulkan/Helpers/Sync.cpp
        src/Engine/Core/System/Iris/Vulkan/Helpers/ImGui.cpp
        src/Engine/Core/System/Iris/Vulkan/Helpers/ImGui.h
        src/Engine/Core/System/Iris/Vulkan/Helpers/CmdBuffs.cpp
        src/Engine/Core/System/Iris/Vulkan/Helpers/CmdBuffs.h
        src/Engine/Types/Rendering/Iris/Statistics.h
        src/Engine/Types/Asset.h
        src/Engine/Core/World/SectorEntry.cpp
        src/Engine/Core/World/SectorEntry.h
        src/Engine/Core/Handlers/SectorHandler.cpp
        src/Engine/Core/Handlers/SectorHandler.h
        src/Engine/Util/TimeAnalysis.cpp
        src/Engine/Util/TimeAnalysis.h
        src/Editor/Core/Handlers/EditorSectorHandler.cpp
        src/Editor/Core/Handlers/EditorSectorHandler.h
        src/Editor/Core/World/EditorSector.cpp
        src/Editor/Core/World/EditorSector.h
        src/Editor/Core/World/EditorSectorEntry.cpp
        src/Editor/Core/World/EditorSectorEntry.h
        src/Engine/Core/RenderPasses/RenderPassBase.cpp
        src/Engine/Core/RenderPasses/RenderPassBase.h
        src/Engine/Core/RenderPasses/ForwardPass.cpp
        src/Engine/Core/RenderPasses/ForwardPass.h
        src/Engine/Core/RenderPasses/ScreenPass.cpp
        src/Engine/Core/RenderPasses/ScreenPass.h
        src/Engine/Core/RenderPasses/Storage/ShaderStore.h
        src/Engine/Core/RenderPasses/Storage/ShaderStore.cpp
        src/Engine/Core/RenderPasses/Storage/Basics.h
        src/Engine/Core/RenderPasses/Storage/Passes.h
        src/Engine/Core/RenderPasses/NormalPass.cpp
        src/Engine/Core/RenderPasses/NormalPass.h
        src/Engine/imgui/ImSequencer.cpp
        src/Engine/imgui/ImLightRig.h
        src/Engine/imgui/ImSequencer.h
        src/Engine/imgui/ImVectorEditor.cpp
        src/Engine/imgui/ImZoomSlider.h
        src/Engine/imgui/ImVectorEditor.h
        src/Engine/imgui/ImGuizmo.h
        src/Engine/imgui/ImGuizmo.cpp
        src/Engine/imgui/ImGradient.h
        src/Engine/imgui/ImGradient.cpp
        src/Engine/imgui/ImCurveEdit.h
        src/Engine/imgui/ImCurveEdit.cpp
        src/Engine/imgui/GraphEditor.h
        src/Engine/imgui/GraphEditor.cpp
        src/Engine/Core/RenderPasses/GTAOPass.cpp
        src/Engine/Core/RenderPasses/GTAOPass.h
        src/Engine/Core/RenderPasses/Storage/GTAOSettings.h
        src/Engine/Types/Audio/Echo/Handles.h
        src/Engine/Core/System/Echo.h
        src/Engine/Types/Audio/Echo/Init.h
        src/Engine/Types/Audio/Echo/Resource.h
        src/Engine/Core/System/Echo/MA/Impl.cpp
        src/Engine/Core/System/Echo/MA/EchoInit.cpp
        src/Engine/Core/System/Echo/MA/EchoResources.cpp
        src/Engine/Core/System/Echo/MA/EchoVirtAudio.cpp
        src/Engine/Core/System/Echo/MA/EchoPlayback.cpp
        src/Engine/Core/System/Echo/MA/EchoBus.cpp
        src/Engine/Core/System/Echo/MA/Helpers/Callback.cpp
        src/Engine/Core/System/Echo/MA/Helpers/Callback.h
        src/Engine/Core/System/Echo/MA/EchoGlobals.h
        src/Engine/Core/System/Echo/MA/Helpers/Types.h
)

target_include_directories(Afterlife_Engine PRIVATE
        src
        ${STEAMWORKS_PATH}/include
)

include(cmake/Defines.cmake)
include(cmake/Thirdparty.cmake)
include(cmake/CompileOptions.cmake)
